CREATE TABLE `Accounts` (
	`Id` int NOT NULL IDENTITY(1,1),
	`[Number]` nvarchar(1073741823),
	`Name` nvarchar(1073741823),
	`Description` nvarchar(1073741823),
	`Active` bit DEFAULT ((1)),
	`Notes` nvarchar(1073741823),
	`ReportLogo` nvarchar(1073741823),
	`AllowNegativeInventory` bit DEFAULT ((1)) NOT NULL,
	`RequireCompletedWorkOrderEffort` bit DEFAULT ((0)) NOT NULL,
	`RequireWorkOrderGroup` bit DEFAULT ((0)) NOT NULL,
	`RequireWorkOrderRequestorPhoneEmail` bit DEFAULT ((0)) NOT NULL,
	`AllowWorkOrderTaskCustomOrderLabels` bit NOT NULL,
	`DisplayRoomInteriors` bit DEFAULT ((1)) NOT NULL,
	`AllowMonitorWorkOrderCreateNotification` bit DEFAULT ((1)) NOT NULL,
	`BasEnabled` bit DEFAULT ((0)) NOT NULL,
	`BasEmailedAlarmEmailPrefix` nvarchar(1073741823),
	`BasCloudKey` uniqueidentifier,
	`BasCloudPassword` nvarchar(1073741823),
	`PasswordAgeLimit` int,
	`InvalidPasswordAttemptLimit` int,
	`PastActivityPasswordLimit` int,
	`PasswordRule` nvarchar(1073741823),
	`AllowWorkOrderRequestorUrgentOption` bit DEFAULT ((0)) NOT NULL,
	`ModifiedOn` datetime DEFAULT (getdate()) NOT NULL,
	`ModifiedById` int DEFAULT ((0)) NOT NULL,
	`CreatedOn` datetime DEFAULT (getdate()) NOT NULL,
	`CreatedById` int DEFAULT ((0)) NOT NULL,
	`AllowWorkOrderRequestorImageCustomProperty` bit DEFAULT ((0)) NOT NULL,
	`RoomView1` nvarchar(50),
	`RoomView2` nvarchar(50),
	`RoomView3` nvarchar(50),
	`RoomView5` nvarchar(1073741823),
	`RoomView6` nvarchar(1073741823),
	`RoomView4` nvarchar(1073741823),

ALTER TABLE `Accounts`
  ADD PRIMARY KEY (`Id`),
  ADD KEY `Id` (`Id`);

CREATE TABLE `WorkOrders` (
	`Id` int NOT NULL IDENTITY(1,1),
	`EventDate` datetime,
	`Title` nvarchar(1073741823),
	`Body` nvarchar(1073741823),
	`Active` bit,
	`AccountId` int,
	`WorkOrderSeriesId` int,
	`Status` nvarchar(1073741823),
	`UserAssignedToId` int,
	`UserGroupAssignedToId` int,
	`Priority` int,
	`Notes` nvarchar(1073741823),
	`EffortEstimated` float,
	`EffortActual` float,
	`CostMaterial` float,
	`AppliesToBuildingId` int,
	`AppliesToAreaId` int,
	`AppliesToRoomId` int,
	`AppliesToEquipmentTypeId` int,
	`AppliesToEquipmentId` int,
	`CreatedOn` datetime,
	`ActivatedOn` datetime,
	`CancelledOn` datetime,
	`CompletedOn` datetime,
	`CreatedById` int,
	`ActivatedById` int,
	`CancelledById` int,
	`CompletedById` int,
	`RefId` int,
	`RefSubId` float,
	`FullRefId` nvarchar(1073741823),
	`WorkOrderProjectId` int,
	`WorkOrderTaskListId` int,
	`MonitorId` int,
	`EmailedAlarmId` int,
	`ModifiedOn` datetime DEFAULT (getdate()) NOT NULL,
	`ModifiedById` int DEFAULT ((0)) NOT NULL,
	`Category` nvarchar(255),
	`Subcategory` nvarchar(255),
	`Details` nvarchar(255)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `WorkOrders`
  ADD PRIMARY KEY (`Id`),
  ADD KEY `AccountId` (`AccountId`);

ALTER TABLE `WorkOrders`
  ADD CONSTRAINT `WorkOrders_ibfk_1` FOREIGN KEY (`AccountId`) REFERENCES `Accounts` (`Id`);
