CREATE TABLE `WorkOrders` (
	`Id` int NOT NULL IDENTITY(1,1),
	`EventDate` datetime,
	`Title` nvarchar(1073741823),
	`Body` nvarchar(1073741823),
	`Active` bit,
	`AccountId` int,
	`WorkOrderSeriesId` int,
	`Status` nvarchar(1073741823),
	`UserAssignedToId` int,
	`UserGroupAssignedToId` int,
	`Priority` int,
	`Notes` nvarchar(1073741823),
	`EffortEstimated` float,
	`EffortActual` float,
	`CostMaterial` float,
	`AppliesToBuildingId` int,
	`AppliesToAreaId` int,
	`AppliesToRoomId` int,
	`AppliesToEquipmentTypeId` int,
	`AppliesToEquipmentId` int,
	`CreatedOn` datetime,
	`ActivatedOn` datetime,
	`CancelledOn` datetime,
	`CompletedOn` datetime,
	`CreatedById` int,
	`ActivatedById` int,
	`CancelledById` int,
	`CompletedById` int,
	`RefId` int,
	`RefSubId` float,
	`FullRefId` nvarchar(1073741823),
	`WorkOrderProjectId` int,
	`WorkOrderTaskListId` int,
	`MonitorId` int,
	`EmailedAlarmId` int,
	`ModifiedOn` datetime DEFAULT (getdate()) NOT NULL,
	`ModifiedById` int DEFAULT ((0)) NOT NULL,
	`Category` nvarchar(255),
	`Subcategory` nvarchar(255),
	`Details` nvarchar(255)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `WorkOrders`
  ADD PRIMARY KEY (`Id`),
  ADD KEY `Id` (`Id`);

